### ISSUE TITLE
Login does not work with custom instance

### ISSUE THREAD

**Issue by SuperSandro2000** [F0x1d/dogbin-mobile#3]
When I try logging in with a custom instance nothing happens and it just changed to the history tab.

**Comment by F0x1d** [comment]
It should work if your custom instance is a full copy of dogbin, including cookie names and html page structure. Because dogbin mobile uses cookies and pages' html structure to work with dogbin.

**Comment by SuperSandro2000** [comment]
Yeah, it works. Thanks!
